general:
  report_frequency: 1
  enable_wandb_hook: 1
  verbose: 1

algorithm:
  type: td3
  parameters:
    batch_size: 512
    num_critics: 2
    policy_lag: 2
    nstep: 1
    nstep_reward_reduction: sum_no_skip
    gamma: 0.99
    rho: 0.99

actor:
  type: space_noise
  parameters:
    a_low: -1.0
    a_high: 1.0
    clip: 0.3
    sigma_train: 0.1
    sigma_explore: 0.2
    adaptive: 0

replay_buffer:
  type: uniform
  parameters:
    max_size: 50000
    min_size: 1024
  
policy_model:
  type: torchscript
  parameters:
    filename: policy.pt

critic_model:
  type: torchscript
  parameters:
    filename: value.pt

optimizer:
  type: adam
  parameters:
    learning_rate: 0.001
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0
    eps: 1e-6
    amsgrad: 0

policy_lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 500000000

critic_lr_scheduler:
  type: cosine_annealing
  parameters:
    T_max: 500000000
