name: "Build"

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "CPU build (GNU, Ubuntu 22.04)"
            dockerfile: "Dockerfile_gnu_cpuonly"

    name: ${{ matrix.name }}
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Build docker container"
      run: |
        docker build -t container -f ${{ matrix.dockerfile }} .
