name: "Build"

on:
  #issue_comment:
  #  types: [created]
  pull_request:
    branches: [ master ]

jobs:
  build:
    #if: github.event.issue.pull_request && contains(github.event.comment.body, '/build_and_test')
    strategy:
      matrix:
        include:
          - name: "GPU build (NVHPC SDK 25.7, Ubuntu 22.04)"
            dockerfile: "Dockerfile"
            run_tests: false
          - name: "GPU build (GNU, Ubuntu 22.04)"
            dockerfile: "Dockerfile_gnu"
            run_tests: false
          - name: "CPU build (GNU, Ubuntu 22.04)"
            dockerfile: "Dockerfile_gnu_cpuonly"
            run_tests: true

    name: ${{ matrix.name }}
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Build docker container"
      run: |
        docker build -t torchfort -f docker/${{ matrix.dockerfile }} .

    - name: "Run tests"
      if: ${{ matrix.run_tests }} == true
      run: |
        docker run --rm torchfort bash -c "
          cd /opt/torchfort/bin/tests/general
          python scripts/setup_tests.py
          ./test_losses
          cd /opt/torchfort/bin/tests/supervised
          python scripts/setup_tests.py
          ./test_checkpoint
          ./test_training
          cd /opt/torchfort/bin/tests/rl
          ./test_distributions
          ./test_replay_buffer
          ./test_rollout_buffer
        "
