name: "Build"

on:
  issue_comment:
    types: [created]

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: "CPU build (GNU, Ubuntu 22.04)"
            dockerfile: "Dockerfile_gnu_cpuonly"

    name: ${{ matrix.name }}
    if: github.event.issue.pull_request && contains(github.event.comment.body, '/build_and_test')
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: "Build docker container"
      run: |
        docker build -t container -f ${{ matrix.dockerfile }} .
